/*
 * Copyright 2025 IBM Corporation
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.chat.interceptor;

import java.util.Optional;
import com.ibm.watsonx.ai.chat.BaseChatRequest;
import com.ibm.watsonx.ai.chat.ChatProvider;
import com.ibm.watsonx.ai.chat.ChatResponse;

/**
 * Provides contextual services and utilities available to interceptors during chat processing.
 *
 * @param <R> the concrete chat request type handled by the intercepted provider
 */
public final class InterceptorContext<R extends BaseChatRequest> {
    private final ChatProvider<R, ?> chatProvider;
    private final R request;
    private final ChatResponse response;

    public InterceptorContext(ChatProvider<R, ?> chatProvider, R request, ChatResponse response) {
        this.chatProvider = chatProvider;
        this.request = request;
        this.response = response;
    }

    /**
     * Returns the chat request that produced the intercepted response.
     *
     * @return the chat request
     */
    public R request() {
        return request;
    }

    /**
     * Returns the {@link ChatResponse}.
     *
     * @return the chat response
     */
    public Optional<ChatResponse> response() {
        return Optional.ofNullable(response);
    }

    /**
     * Sends a request to an LLM for auxiliary processing.
     * <p>
     * This method enables interceptors to perform additional reasoning steps, validation passes, rewriting, classification, or any other operation
     * assisted by the language model.
     *
     * @param request the chat request to execute
     * @return the response generated by the model
     */
    public ChatResponse invoke(R request) {
        return chatProvider.chat(request);
    }
}
