/*
 * Copyright 2025 IBM Corporation
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.chat.interceptor;

import java.util.Optional;
import com.ibm.watsonx.ai.chat.ChatProvider;
import com.ibm.watsonx.ai.chat.ChatRequest;
import com.ibm.watsonx.ai.chat.ChatResponse;

/**
 * Provides contextual services and utilities available to interceptors during chat processing.
 */
public final class InterceptorContext {
    private final ChatProvider chatProvider;
    private final ChatRequest request;
    private final ChatResponse response;

    public InterceptorContext(ChatProvider chatProvider, ChatRequest request, ChatResponse response) {
        this.chatProvider = chatProvider;
        this.request = request;
        this.response = response;
    }

    /**
     * Returns the {@link ChatRequest}.
     *
     * @return the chat request
     */
    public ChatRequest request() {
        return request;
    }

    /**
     * Returns the {@link ChatResponse}.
     *
     * @return the chat response
     */
    public Optional<ChatResponse> response() {
        return Optional.ofNullable(response);
    }

    /**
     * Sends a request to an LLM for auxiliary processing.
     * <p>
     * This method enables interceptors to perform additional reasoning steps, validation passes, rewriting, classification, or any other operation
     * assisted by the language model.
     *
     * @param request the chat request to execute
     * @return the response generated by the model
     */
    public ChatResponse invoke(ChatRequest request) {
        return chatProvider.chat(request);
    }
}
