/*
 * Copyright IBM Corp. 2025 - 2025
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.chat.interceptor;

import static java.util.Objects.isNull;
import java.util.List;
import com.ibm.watsonx.ai.chat.ChatResponse;
import com.ibm.watsonx.ai.chat.ChatResponse.ResultChoice;
import com.ibm.watsonx.ai.chat.model.CompletedToolCall;
import com.ibm.watsonx.ai.chat.model.FunctionCall;
import com.ibm.watsonx.ai.chat.model.ResultMessage;

/**
 * Functional interface for intercepting and modifying tool calls produced by an assistant.
 * <p>
 * This interceptor is invoked for every tool call generated by the model. Implementations can transform arguments, adjust metadata, or modify the
 * call before it is executed or returned.
 * <p>
 * <b>Example usage:</b>
 *
 * <pre>{@code
 * ToolInterceptor interceptor =
 *     (ctx, fc) -> {
 *         var args = fc.arguments();
 *         return args != null && args.startsWith("\"")
 *             ? fc.withArguments(Json.fromJson(args, String.class))
 *             : fc;
 *     };
 * }</pre>
 */
@FunctionalInterface
public interface ToolInterceptor {

    /**
     * Intercepts and modifies a single tool call.
     *
     * @param ctx the interceptor context, providing access to request, response, and other contextual information
     * @param fc the tool call to intercept
     * @return the modified tool call
     */
    FunctionCall intercept(InterceptorContext ctx, FunctionCall fc);

    /**
     * Applies this interceptor to all tool calls in the given {@link ChatResponse}.
     *
     * @param context the interceptor context containing the current request and response
     * @return a list of {@link ResultChoice} containing rebuilt messages with applied tool call transformations
     */
    default List<ResultChoice> intercept(InterceptorContext context) {
        var response = context.response().orElseThrow();
        return response.choices().stream().map(choice -> {

            var message = choice.message();

            if (isNull(message.toolCalls()))
                return choice;

            var toolCalls = message.toolCalls();
            var normalized = toolCalls.stream()
                .map(tc -> intercept(context, tc.function()))
                .toList();

            var rebuiltToolCalls = toolCalls.stream()
                .flatMap(tc -> normalized.stream().map(fc -> tc.withFunctionCall(fc)))
                .toList();

            var resultMessage = new ResultMessage(
                message.role(),
                message.content(),
                message.reasoningContent(),
                message.refusal(),
                rebuiltToolCalls
            );

            return choice.withResultMessage(resultMessage);
        }).toList();
    }

    /**
     * Applies the interceptor to a full {@link CompletedToolCall}, returning a new instance with the modified tool call.
     *
     * @param context the interceptor context containing the current request and response
     * @param completedToolCall the completed tool call to intercept
     * @return a new {@link CompletedToolCall} containing the modified tool call
     */
    default CompletedToolCall intercept(InterceptorContext context, CompletedToolCall completedToolCall) {
        var normalized = intercept(context, completedToolCall.toolCall().function());
        return new CompletedToolCall(
            completedToolCall.completionId(),
            completedToolCall.index(),
            completedToolCall.toolCall().withFunctionCall(normalized)
        );
    }
}