/*
 * Copyright IBM Corp. 2025 - 2025
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.runtime.chat.model;

import java.util.List;

/**
 * Represents a message returned from the chat model after processing input.
 * <p>
 * A {@code ResultMessage} can include the assistant's role, generated content, optional refusal reasons, and any tool calls that should be executed.
 *
 * @param role the role of the message sender (e.g., "assistant", "user", "system")
 * @param content the textual content of the message
 * @param refusal the refusal message generated by the model
 * @param toolCalls list of tool calls
 */
public record ResultMessage(String role, String content, String refusal, List<ToolCall> toolCalls) {
}
