/*
 * Copyright 2025 IBM Corporation
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.gateway.image;

import static java.util.Objects.isNull;
import java.util.List;

/**
 * Response returned by the Model Gateway image generation endpoint.
 *
 * @param created the UNIX timestamp in seconds of when the response was created
 * @param data the list of generated image objects
 * @param background the background setting used for the generated images, never {@code "auto"}
 * @param outputFormat the output format of the generated images, never {@code "auto"}
 * @param quality the quality of the generated images, never {@code "auto"}
 * @param size the size of the generated images, never {@code "auto"}
 * @param usage the token usage information, or {@code null} if not returned
 */
public record ModelGatewayImageResponse(
    long created,
    List<ImageData> data,
    String background,
    String outputFormat,
    String quality,
    String size,
    Usage usage) {

    public ModelGatewayImageResponse {
        data = isNull(data) ? null : List.copyOf(data);
    }

    /**
     * Represents a single generated image object.
     *
     * @param url the URL of the image, or {@code null} when the {@code "b64_json"} format was requested
     * @param b64Json the Base64-encoded image data, or {@code null} when the {@code "url"} format was requested
     * @param revisedPrompt the revised prompt used for generation, if any
     */
    public record ImageData(String url, String b64Json, String revisedPrompt) {}

    /**
     * Token usage information for the image generation request.
     *
     * @param inputTokens the number of tokens, images and text, in the input prompt
     * @param outputTokens the number of output tokens generated by the model
     * @param totalTokens the total number of tokens used
     * @param inputTokensDetails detailed breakdown of input token usage
     */
    public record Usage(long inputTokens, long outputTokens, long totalTokens, InputTokensDetails inputTokensDetails) {}

    /**
     * Detailed breakdown of input tokens.
     *
     * @param imageTokens the number of image tokens in the input prompt
     * @param textTokens the number of text tokens in the input prompt
     */
    public record InputTokensDetails(long imageTokens, long textTokens) {}
}
