/*
 * Copyright 2025 IBM Corporation
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.gateway.embedding;

import static java.util.Objects.isNull;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

/**
 * Response returned by the Model Gateway embeddings endpoint.
 *
 * @param object the object type, which is always {@code "list"}
 * @param model the id of the model used to create the embeddings
 * @param data the list of embedding objects generated by the model
 * @param usage the token usage information for the request
 */
public record ModelGatewayEmbeddingResponse(String object, String model, List<Embedding> data, Usage usage) {

    /**
     * Represents token usage information for an embedding request.
     *
     * @param promptTokens the number of tokens in the prompt
     * @param totalTokens the total number of tokens used in the request
     */
    public record Usage(int promptTokens, int totalTokens) {}

    /**
     * Represents a single embedding object returned by the model.
     *
     * @param object the object type, which is always {@code "embedding"}
     * @param index the index of this embedding in the input list
     * @param embedding the embedding vector, decoded from Base64 when the {@code "base64"} encoding format was requested, copied and exposed as an
     *            unmodifiable list
     * @param base64 the raw Base64 payload, or {@code null} when the {@code "float"} encoding format was used
     */
    public record Embedding(String object, int index, List<Float> embedding, String base64) {

        public Embedding {
            embedding = isNull(embedding) ? null : List.copyOf(embedding);
        }

        /**
         * Creates an {@link Embedding} from the raw value returned by the gateway.
         *
         * @param object the object type
         * @param index the index of this embedding in the input list
         * @param value a list of numbers for the {@code "float"} format, or a Base64 string for the {@code "base64"} format
         * @return a new {@link Embedding}
         */
        static Embedding of(String object, int index, Object value) {

            if (isNull(value))
                return new Embedding(object, index, null, null);

            if (value instanceof String base64)
                return new Embedding(object, index, decode(base64), base64);

            if (value instanceof List<?> vector)
                return new Embedding(object, index, toFloats(vector), null);

            throw new IllegalArgumentException(
                "Unsupported embedding value of type %s".formatted(value.getClass().getName()));
        }

        /**
         * Returns the embedding in the same shape the gateway sent it.
         *
         * @return the Base64 payload, or the vector when the {@code "float"} format was used
         */
        Object rawEmbedding() {
            return isNull(base64) ? embedding : base64;
        }

        /**
         * Decodes a Base64 payload into the little-endian {@code float32} vector it represents.
         *
         * @param base64 the Base64 payload
         * @return the decoded vector
         */
        private static List<Float> decode(String base64) {
            var bytes = Base64.getDecoder().decode(base64);

            if (bytes.length % Float.BYTES != 0)
                throw new IllegalArgumentException(
                    "Invalid base64 embedding: %s bytes is not a multiple of %s".formatted(bytes.length, Float.BYTES));

            var floats = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer();
            var values = new ArrayList<Float>(floats.remaining());

            while (floats.hasRemaining())
                values.add(floats.get());

            return values;
        }

        /**
         * Converts the numbers returned by the {@code "float"} encoding format into a vector of floats.
         *
         * @param vector the raw list of numbers
         * @return the converted vector
         */
        private static List<Float> toFloats(List<?> vector) {
            var values = new ArrayList<Float>(vector.size());

            for (var value : vector) {
                if (!(value instanceof Number number))
                    throw new IllegalArgumentException(
                        "Invalid embedding vector: expected a number but found %s".formatted(value));
                values.add(number.floatValue());
            }

            return values;
        }
    }
}
