/*
 * Copyright IBM Corp. 2025 - 2025
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.transcription;

/**
 * Represents the result returned by the watsonx.ai Transcribe Audio API.
 *
 * @param model The model used for audio transcription.
 * @param text The text generated by transcribing the input audio.
 * @param createdAt The ISO 8601 timestamp indicating when the transcription result was created.
 * @param tokenCount The number of estimated tokens in the returned text.
 */
public record TranscriptionResult(String model, String text, String createdAt, int tokenCount) {}
