Args = --initialize-at-build-time=com.ibm.watsonx.ai.core.exception.model.WatsonxError$Code \
       --initialize-at-run-time=com.ibm.watsonx.ai.core.Json \
       --initialize-at-run-time=com.ibm.watsonx.ai.core.provider.ExecutorProvider
