/*
 * Copyright IBM Corp. 2025 - 2025
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.chat.model;

/**
 * Represents a function call generated by the model.
 * <p>
 * Contains the function name and the arguments in JSON format as produced by the model.
 *
 * <pre>{@code
 * FunctionCall call = FunctionCall.of(
 *     "sum",
 *     "{\"first_number\": 2, \"second_number\": 2}"
 * );
 * }</pre>
 *
 * @param name The name of the function.
 * @param arguments The arguments to call the function with, as generated by the model in JSON format.
 */
public record FunctionCall(String name, String arguments) {


    /**
     * Factory method to create a new {@link FunctionCall}.
     *
     * @param name The function name
     * @param arguments JSON-formatted arguments
     * @return a new {@link FunctionCall} instance
     */
    public static FunctionCall of(String name, String arguments) {
        return new FunctionCall(name, arguments);
    }

    /**
     * Returns a copy of this {@link FunctionCall} with a new name.
     *
     * @param newName the new function name
     * @return a new {@link FunctionCall} instance
     */
    public FunctionCall withName(String newName) {
        return new FunctionCall(newName, arguments);
    }

    /**
     * Returns a copy of this {@link FunctionCall} with new arguments.
     *
     * @param newArguments the new JSON arguments
     * @return a new {@link FunctionCall} instance
     */
    public FunctionCall withArguments(String newArguments) {
        return new FunctionCall(name, newArguments);
    }
}
