/*
 * Copyright IBM Corp. 2025 - 2025
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.chat.model;

/**
 * Represents a function call generated by the model.
 * <p>
 * Contains the function name and the arguments in JSON format as produced by the model.
 *
 * <pre>{@code
 * FunctionCall call = FunctionCall.of(
 *     "sum",
 *     "{\"first_number\": 2, \"second_number\": 2}"
 * );
 * }</pre>
 *
 * @param name The name of the function.
 * @param arguments The arguments to call the function with, as generated by the model in JSON format.
 */
public record FunctionCall(String name, String arguments) {

    /**
     * Create a new {@link FunctionCall}.
     *
     * @param name The name of the function.
     * @param arguments The arguments to call the function with, as generated by the model in JSON format.
     * @return {@link FunctionCall}
     */
    public static FunctionCall of(String name, String arguments) {
        return new FunctionCall(name, arguments);
    }
}
