/*
 * Copyright 2025 IBM Corporation
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.chat.model;

import java.util.List;

/**
 * Represents a message returned from the chat model after processing input.
 * <p>
 * A {@code ResultMessage} can include the assistant's role, generated content, optional refusal reasons, and any tool calls that should be executed.
 *
 * @param role the role of the message
 * @param content the textual content of the message
 * @param reasoningContent the reasoning content generated by the LLM
 * @param refusal the refusal message generated by the model
 * @param toolCalls list of tool calls
 */
public record ResultMessage(
    String role,
    String content,
    String reasoningContent,
    String refusal,
    List<ToolCall> toolCalls) {

    /**
     * Creates a new {@code ResultMessage} with the specified tool calls, preserving all other fields.
     *
     * @param newToolCalls the new list of tool calls to use in the returned message
     * @return a new {@code ResultMessage} instance with the updated tool calls
     */
    public ResultMessage withToolCalls(List<ToolCall> newToolCalls) {
        return new ResultMessage(role, content, reasoningContent, refusal, newToolCalls);
    }
}
