/*
 * Copyright IBM Corp. 2025 - 2025
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonx.ai.chat.model;

import static java.util.Objects.nonNull;
import java.util.Map;
import com.ibm.watsonx.ai.chat.ToolExecutor;
import com.ibm.watsonx.ai.core.Json;
import com.ibm.watsonx.ai.core.spi.json.TypeToken;

/**
 * Represents a tool call generated by the model, such as a function call.
 * <p>
 * When multiple tool calls are present in a single response, each tool call is identified by its {@code index}. This allows the model to request
 * multiple function executions in a single turn.
 * <p>
 * <b>Example usage:</b>
 *
 * <pre>{@code
 * ToolCall toolCall = ToolCall.of("call-123", "search", "{\"query\":\"openai\"}");
 * }</pre>
 *
 * @param index The index of this tool call within the list of tool calls
 * @param id The unique identifier of the tool call
 * @param type The type of tool call, always {@code function}
 * @param function The function call details
 */
public record ToolCall(Integer index, String id, String type, FunctionCall function) {

    public static final String TYPE = "function";

    public ToolCall {
        type = TYPE;
    }

    /**
     * Creates a new {@link ToolCall} instance.
     *
     * @param id The unique identifier of the tool call.
     * @param name The name of the function to call.
     * @param arguments The arguments to call the function with, as generated by the model in JSON format.
     * @return A new {@link ToolCall} instance.
     */
    public static ToolCall of(String id, String name, String arguments) {
        return of(null, id, name, arguments);
    }

    /**
     * Creates a new {@link ToolCall} instance.
     *
     * @param index The tool index.
     * @param id The unique identifier of the tool call.
     * @param name The name of the function to call.
     * @param arguments The arguments to call the function with, as generated by the model in JSON format.
     * @return A new {@link ToolCall} instance.
     */
    public static ToolCall of(Integer index, String id, String name, String arguments) {
        return new ToolCall(index, id, TYPE, FunctionCall.of(name, arguments));
    }

    /**
     * Returns a copy of this {@link ToolCall} with the specified {@link FunctionCall}.
     *
     * @param newFunctionCall the new {@link FunctionCall} to associate with this tool call
     * @return a new {@link ToolCall} instance with the updated function
     */
    public ToolCall withFunctionCall(FunctionCall newFunctionCall) {
        return new ToolCall(index, id, TYPE, newFunctionCall);
    }

    /**
     * Processes the tool call using the provided {@link ToolExecutor}.
     *
     * @param executor the executor responsible for running the tool call logic
     * @return {@link ToolMessage} object generated from the tool call
     */
    public ToolMessage processTool(ToolExecutor executor) {

        ToolArguments toolArguments = null;
        if (nonNull(function.arguments())) {

            var arguments = function.arguments().startsWith("\"")
                ? Json.fromJson(function.arguments(), String.class)
                : function.arguments();

            toolArguments = new ToolArguments(Json.fromJson(arguments, new TypeToken<Map<String, Object>>() {}));
        }

        var toolResult = String.valueOf(executor.execute(function.name(), toolArguments));
        return ToolMessage.of(toolResult, id);
    }
}
