Args = --initialize-at-build-time=com.ibm.watsonx.ai.WatsonxJacksonModule \
       --initialize-at-build-time=com.ibm.watsonx.ai.chat.model.FinishReason \
       --initialize-at-build-time=com.ibm.watsonx.ai.chat.model.BaseChatParameters$ResponseFormat \
       --initialize-at-build-time=com.ibm.watsonx.ai.chat.model.BaseChatParameters$ToolChoiceOption \
       --initialize-at-build-time=com.ibm.watsonx.ai.batch.Status \
       --initialize-at-build-time=com.ibm.watsonx.ai.file.Order \
       --initialize-at-build-time=com.ibm.watsonx.ai.file.Purpose \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.CosUrl \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.Language \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.Mode \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.OcrMode \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.Status \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.textextraction.TextExtractionParameters$Type \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.textextraction.TextExtractionParameters$EmbeddedImageMode \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.textextraction.TextExtractionParameters$KvpMode \
       --initialize-at-build-time=com.ibm.watsonx.ai.textprocessing.textclassification.TextClassificationParameters$ClassificationMode \
       --initialize-at-build-time=com.ibm.watsonx.ai.chat.model.ThinkingEffort \
       --initialize-at-build-time=com.ibm.watsonx.ai.foundationmodel.FoundationModelTask
