name: Deploy GitHub Pages

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Build Docusaurus site
        run: npm run build
        working-directory: docs

      - name: Upload static files
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/build

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
